package com.algora.app.feature.interviewprep.quiz

import com.algora.app.core.data.model.Difficulty

internal val timedMockInterview = Quiz(
    id = "timed_mock_interview",
    title = "Timed Mock Interview",
    description = "Six mixed-pattern questions under a five-minute clock. Pick the best approach for each.",
    timeLimitSeconds = 300,
    questions = listOf(
        QuizQuestion(
            prompt = "Longest substring without repeating characters — the optimal approach is:",
            options = listOf(
                "A sliding window with a last-seen index map",
                "Sort the string, then scan for duplicates",
                "Check every substring for uniqueness",
                "Binary search on the answer length",
            ),
            correctIndex = 0,
            patternTag = "Sliding Window",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Expand the window's right edge; when a repeat appears, jump the left edge past the previous occurrence. O(n) time, O(min(n, alphabet)) space.",
            linkedTopicId = "sliding_window",
            linkedTopicLabel = "Sliding Window",
        ),
        QuizQuestion(
            prompt = "In a sorted array, find two numbers summing to a target in O(n) time and O(1) space:",
            options = listOf(
                "Two pointers, one from each end",
                "A hash map of complements",
                "Two nested loops",
                "Binary search for each element",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.BEGINNER,
            explanation = "Move the left pointer right when the sum is too small and the right pointer left when it's too big. The hash-map answer is O(n) time but O(n) space.",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
        QuizQuestion(
            prompt = "Worst-case comparisons to binary-search a sorted array of ~1,000,000 elements:",
            options = listOf("About 20", "About 1,000", "About 500,000", "About 1,000,000"),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.BEGINNER,
            explanation = "Binary search is O(log₂ n). log₂(1,000,000) ≈ 20, so at most ~20 comparisons.",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Maximum contiguous subarray sum in a single O(n) pass:",
            options = listOf(
                "Kadane's algorithm",
                "Sort then take the suffix",
                "All-pairs prefix sums",
                "Depth-first search",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Kadane keeps a running best-ending-here sum, resetting when it drops below zero. O(n) time, O(1) space.",
            linkedTopicId = "kadanes_algorithm",
            linkedTopicLabel = "Kadane's Algorithm",
        ),
        QuizQuestion(
            prompt = "Detect a cycle in a linked list using O(1) extra space:",
            options = listOf(
                "Floyd's fast & slow pointers",
                "Store every visited node in a hash set",
                "Reverse the list and compare",
                "Sort the node addresses",
            ),
            correctIndex = 0,
            patternTag = "Fast & Slow Pointers",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A slow pointer moving one step and a fast pointer moving two will meet inside any cycle. The hash-set approach works but costs O(n) space.",
            linkedTopicId = "singly_linked_list",
            linkedTopicLabel = "Singly Linked List",
        ),
        QuizQuestion(
            prompt = "Fewest coins to make an amount with unlimited denominations:",
            options = listOf(
                "Dynamic programming (coin change)",
                "Always take the largest coin (greedy)",
                "Two pointers over sorted coins",
                "Breadth-first search only",
            ),
            correctIndex = 0,
            patternTag = "Dynamic Programming",
            difficulty = Difficulty.ADVANCED,
            explanation = "Greedy fails for coin systems like {1, 3, 4} making 6. DP over subamounts guarantees the optimum in O(amount × coins).",
            linkedTopicId = "coin_change",
            linkedTopicLabel = "Coin Change",
        ),
    ),
)

internal val faangSet = Quiz(
    id = "faang_set",
    title = "FAANG Set",
    description = "Five company-tagged favourites. Identify the canonical technique for each.",
    timeLimitSeconds = 420,
    questions = listOf(
        QuizQuestion(
            prompt = "Clone an undirected graph given a node reference:",
            options = listOf(
                "BFS/DFS with an original→copy visited map",
                "Topological sort then rebuild",
                "Union-Find over the edges",
                "Dijkstra from the given node",
            ),
            correctIndex = 0,
            patternTag = "Graph Traversal",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Traverse once, creating a copy on first visit and wiring neighbours through the visited map to avoid infinite loops on cycles.",
            companyTag = "Google",
            linkedTopicId = "bfs",
            linkedTopicLabel = "Breadth-First Search",
        ),
        QuizQuestion(
            prompt = "Minimum window substring of S that contains all characters of T:",
            options = listOf(
                "Sliding window with a need/have count",
                "Sort both strings and diff them",
                "Build a trie of T",
                "Binary search the window size",
            ),
            correctIndex = 0,
            patternTag = "Sliding Window",
            difficulty = Difficulty.ADVANCED,
            explanation = "Grow the window until it covers T, then shrink from the left while it still covers T, tracking the smallest. O(|S| + |T|).",
            companyTag = "Meta",
            linkedTopicId = "sliding_window",
            linkedTopicLabel = "Sliding Window",
        ),
        QuizQuestion(
            prompt = "Return the K points closest to the origin:",
            options = listOf(
                "A size-K max-heap (or Quickselect)",
                "Fully sort all points every time",
                "Breadth-first search",
                "Dynamic programming",
            ),
            correctIndex = 0,
            patternTag = "Top-K / Heap",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "A size-K max-heap gives O(n log K); Quickselect gives O(n) average. A full sort is O(n log n) — more work than needed.",
            companyTag = "Amazon",
            linkedTopicId = "top_k_elements",
            linkedTopicLabel = "Top-K Elements",
        ),
        QuizQuestion(
            prompt = "Search for a target in a rotated sorted array in O(log n):",
            options = listOf(
                "Modified binary search on the sorted half",
                "Linear scan from the pivot",
                "Hash every element first",
                "Merge sort then binary search",
            ),
            correctIndex = 0,
            patternTag = "Binary Search",
            difficulty = Difficulty.ADVANCED,
            explanation = "At each step one half is sorted; decide whether the target lies in it and recurse there, keeping O(log n).",
            companyTag = "Google",
            linkedTopicId = "binary_search",
            linkedTopicLabel = "Binary Search",
        ),
        QuizQuestion(
            prompt = "Container With Most Water — maximum area between two lines:",
            options = listOf(
                "Two pointers moving the shorter wall inward",
                "Check every pair of lines",
                "Sort the heights first",
                "A segment tree of heights",
            ),
            correctIndex = 0,
            patternTag = "Two Pointer",
            difficulty = Difficulty.INTERMEDIATE,
            explanation = "Start at both ends; the area is bounded by the shorter wall, so moving it inward is the only way the area can grow. O(n).",
            companyTag = "Meta",
            linkedTopicId = "two_pointer",
            linkedTopicLabel = "Two Pointer Technique",
        ),
    ),
)
